name: ultra_shine
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # CORE PACKAGES
  http: ^0.13.4
  get: ^4.3.8
  shared_preferences: ^2.0.9
  intl: ^0.17.0
  flutter_local_notifications: ^9.1.4
  flutter_screenutil: ^5.0.0+2

  # IMAGES
  cached_network_image: ^3.1.0+1

  # FIREBASE
  firebase_core: ^1.10.0
  firebase_messaging: ^11.1.0

  # SOCIAL AUTH
  google_sign_in: ^5.2.1
  flutter_facebook_auth: ^3.5.6

  # HIVE
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.1

  # EXTRAS
  url_launcher: ^6.0.15
  google_fonts: ^2.1.0
  im_stepper: ^0.1.3
  timeline_tile: ^2.0.0
  flutter_rating_bar: ^4.0.0

  # ANIMATIONS
  animated_splash_screen: ^1.1.0
  page_transition:

  #IMAGEPICKER
  image_picker: ^0.8.4+4
  file_picker: ^4.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  assets:
     - assets/icons/
     - assets/images/
  #   - images/a_dot_ham.jpeg
